server:
  port: ${adminServicePort}

spring:
  application:
    name: ${adminApiModuleName}
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  main:
    allow-bean-definition-overriding: true # FeignClient value 可以重名
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  resources:
    static-locations: classpath:/static/, classpath:/html/

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${eurekaServerPort}/eureka/

feign:
  hystrix:
    enabled: true
