spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dmp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

generator:
  encoding: UTF-8
  table-name-match-regex: '(?<=dmp_).*'
  paths:
    template: /Users/xi/Projects/github.com/java/code-generator/templates/template3/                   # 模版路径
    out: /Users/xi/Projects/                          # 输出路径
  files:
    ignore: include/, .DS_Store
    aggregate: src/router/index.ts.ftl, views/Home.vue
    copy: public/favicon.ico, public/index.html, src/assets/, src/components/, src/composables/, src/mixin/, src/store/, src/utils/, src/App.vue, src/base_config.js, src/main.js, .browserslistrc, .eslintrc.js, .gitignore, babel.config.js, package.json, tsconfig.json, vue.config.js

  columns:
    base:
      column-name-set: deleted, create_user, create_username, update_user, update_username, create_time, update_time
      table-name: dmp_sys_config
    not-required:
      - column-name-set: create_time, update_time, ext_info
#    img-url:
#    video-url:
#    doc-url:
#    page-url:
#    other-url:
    content:
      - column-name-set: remark, ext_info
      - column-name-set: value
        table-name: dmp_sys_config

    valid-status:
      - column-name-set: deleted
        status:
          valid: 0
          invalid: 1

    select:
      - column-name-set: type
        table-name: dmp_sys_role
        options:
          - value: 1
            text: 系统角色
          - value: 2
            text: 数据角色
      - column-name-set: type
        table-name: dmp_sys_permission
        options:
          - value: 0
            text: 权限分组
          - value: 1
            text: 权限
      - column-name-set: path_type
        table-name: dmp_sys_menu
        options:
          - value: 0
            text: vue路由
          - value: 1
            text: 相对路径
          - value: 2
            text: 绝对路径
      - column-name-set: type
        table-name: dmp_sys_menu
        options:
          - value: 0
            text: 目录
          - value: 1
            text: 菜单
      - column-name-set: type
        table-name: dmp_sys_option
        options:
          - value: 0
            text: 目录
          - value: 1
            text: 菜单
      - column-name-set: type
        table-name: dmp_sys_config
        options:
          - value: 0
            text: 后台配置
          - value: 1
            text: 页面配置
      - column-name-set: operator_type
        options:
          - value: 1
            text: 用户
          - value: 2
            text: 部门
          - value: 3
            text: 角色

    fk-select:
      - column-name-set: module_id
        table-name: dmp_sys_menu
        fk:
          foreign-table-name: dmp_sys_module
          value-column-name: module_id
          text-column-name: module_name
      - column-name-set: dept_id
        table-name: dmp_sys_user
        fk:
          foreign-table-name: dmp_sys_dept
          value-column-name: id
          text-column-name: dept_name

  # 公共自定义属性
  common-properties:
    projectName: dmp
    module: sys
    serviceApplicatioName: DmpSysApplication
    servicePort: 8080
    modulePackage: org.xi.dmp.sys
    commonPackage: org.xi.dmp.common

    author: 郗世豪（rarexixi@sina.com）
    javaSrc: src/main/java
    javaTestSrc: src/test/java
    resourcesSrc: src/main/resources

  # 获取数据映射关系
  data-type-map:
    tinyint: Integer
    smallint: Integer
    int: Integer
    bigint: Long
    float: Float
    double: Double
    decimal: BigDecimal
    numeric: BigDecimal
    bit: Boolean
    character: Character
    varchar: String
    char: String
    text: String
    date: LocalDate
    datetime: LocalDateTime
    timestamp: LocalDateTime